name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        
        import sys
        
        data = line.strip().split("\t")
        
        date, time, store, item, cost, payment = data
        
        print "{0}\t{1}".format(item, cost)
        
        from datetime import timedelta
        
        from datetime import timedelta
        
        d = timedelta(microseconds==1)
        (d.days, d.seconds, d.microseconds)
        
        datetime_object = datetime.now()
        
        print(datetime_object)
        
        print('Type :- ',type(datetime_object))
